config/routes.rb
Rails.application.routes.draw do
  
  resources :users

  resources :reviews

  get 'pages/home'
  
  get 'pages/about'
  

  get '/pages/:page' => 'pages#show'
  
  resources :albums

  resources :artists

  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
  end
 
  get 'search' => 'albums#search'
  

  root 'pages#home'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :albums
	

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :bio, :image)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<div class="container">
<div class="jumbotron">
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>
	<li>
	<div id="search">
	   <%= render 'search' %>
    </div></li>
      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Artists</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">

	
  <h1>Artists</h1>
  
  <hr>
  <% @artists.each do |artist| %>
  <div class="row">
    <div class="col-xs-3">
        <a href="#" class="thumbnail">
             <%= image_tag artist.image, :size => "200x200" %>
        </a>
		<ul class="list-inline">
		<li><a href="#" title="<%= artist.name %>" data-toggle="popover" data-placement="top" data-content="  <%= artist.bio %> "> <%= artist.name %></a></li>
		
		
	   <li><%= link_to 'Show Artist', artist %></li>
       <li><%= link_to 'Edit', edit_artist_path(artist) %></li>
      <li> <%= link_to 'Destroy', @artist, method: :delete, data: { confirm: 'Are you sure?' } %></li>
	  
    </div>
	
    <tbody>


		</ul>
  <% end %>
</div>

<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();   
});
</script>
    
<%= button_to('New Artist', new_artist_path, class: 'btn btn-large btn-primary', method: :get) %>
<%= button_to('View Artist', artists_path, class: 'btn btn-large btn-primary', method: :get) %>


</body>


</html>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Artists</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Artists</h2>       
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Photo</th>
        <th>Bio</th>
      </tr>
    </thead>
    <tbody>
	
      <tr>
       <td> <%= @artist.name %></td>
       <td> <%= image_tag @artist.image %></td>
       <td> <%= @artist.bio %></td>
      </tr>
	 
    </tbody>
	
	
     
  </table>
</div>

</body>
</html>