config/routes.rb
Rails.application.routes.draw do
  
  resources :users

  resources :reviews

  get 'pages/home'
  
  get 'pages/about'
  

  get '/pages/:page' => 'pages#show'
  
  resources :albums

  resources :artists

  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
  end
 
  get 'search' => 'albums#search'
  

  root 'pages#home'

end

app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :artists
	
	has_many :reviews
	
	def self.search(query)
		where("column LIKE ?", "%#{query}%") #whatever column you want to search on
	end
	def self.search(search)
		where("col1 LIKE ?", "%#{query}%") #this searches the contents of the 2 columns
		where("col2 LIKE ?", "%#{query}%") # using OR
	end

	

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_filter :authorise, only: [:new, :edit, :update, :destroy]
 #@albums = Albums.paginate(:page => params[:page], :per_page => 2)
  
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :artist_id, :songs, :picture, :musicVideo)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<div class="container">
<div class="jumbotron">
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>
	  

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :artist_id %><br>
	<%=f.collection_select :artist_id, Artist.all, :id, :name %>
    
  </div>
  <div class="field">
    <%= f.label :songs %><br>
    <%= f.text_area :songs %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :musicVideo %><br>
    <%= f.text_area :musicVideo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
  </div>
<% end %>

app/views/albums/_search.html.erb
<%= form_tag(search_path, :method => "get") do %> 
<%= text_field_tag(:query, params[:query]) %> 
<%= submit_tag "Search" %>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Albums</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">


	<div id= 'search' align="center">
		<%= render 'search' %>
    </div>
  <h1>Albums</h1>
  
  
  <hr>
  
  
  <% @albums.each do |album| %>
  <div class="row">
    <div class="col-xs-3">
        <a href="<%=  album.musicVideo %>" class="thumbnail">
             <%= image_tag album.picture, :size => "200x200" %>
        </a>
		<ul class="list-inline">
		<li><a href="#" title="<%= album.name %>" data-toggle="popover" data-placement="top" data-content=" Number of Songs:  <%= album.songs %> "> <%= album.name %></a></li>
		<li><a href="<%= album.musicVideo %>"> Music Video</a></li>
		
	   <li><%= link_to 'Show Album', album %></li>
       <li><%= link_to 'Edit', edit_album_path(album) %></li>
      <li> <%= link_to 'Destroy', @album, method: :delete, data: { confirm: 'Are you sure?' } %></li>
	  <li> <%= link_to 'Post a review for this album!', new_review_path %></li>
    </div>
	
    <tbody>


		</ul>
  <% end %>
</div>

<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();   
});
</script>
    
<%= button_to('New Album', new_album_path, class: 'btn btn-large btn-primary', method: :get) %>
<%= button_to('See all reviews', reviews_path, class: 'btn btn-large btn-primary', method: :get) %>


</body>


</html>


app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Albums</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Albums</h2>       
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Artist</th>
		<th>Number of Songs</th>
		<th>Picture</th>
		<th>Music Video</th>
        
      </tr>
    </thead>
    <tbody>

      <tr>
       <td> <%= @album.name %> </td>
       <td> <%= @album.artist_id %> </td>
       <td> <%= @album.songs %> </td>
	   <td> <%= image_tag @album.picture, :size => "200x200" %> </td>
	   <td> <%= sanitize @album.musicVideo, :tags => ['iframe'] %> </td>
	   
	   <td><%= link_to 'Show', @album %></td>
       <td><%= link_to 'Edit', edit_album_path %></td>
       <td><%= link_to 'Destroy', @album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	   <td><%= link_to 'Post a review for this album!', reviews_path %></td>
	   
	   
      </tr>
	 
    </tbody>

  </table>
</div>

</body>

</html>

<%= button_to('New Album', new_album_path, class: 'btn btn-large btn-primary', method: :get) %>
<%= button_to('View Albums', albums_path, class: 'btn btn-large btn-primary', method: :get) %>
<%= button_to('See all reviews', reviews_path, class: 'btn btn-large btn-primary', method: :get) %>








	
	

</body>
</html>