config/routes.rb
Rails.application.routes.draw do
  
  resources :users

  resources :reviews

  get 'pages/home'
  
  get 'pages/about'
  

  get '/pages/:page' => 'pages#show'
  
  resources :albums

  resources :artists

  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
  end
 
  get 'search' => 'albums#search'
  

  root 'pages#home'

end

app/views/layouts/application.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/#">S|TUNES</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%=mail_to "Sarah.brett123@gmail.com", "Mail" %></li>
      <li><%=link_to "Latest Music", 'http://www.itunes.com' %></li>
	  <li><%=link_to "All Albums", albums_path %></li>
	  <li><%=link_to "All Artists", artists_path	%></li>
	  
	
    </ul>
  </div>
  
 <% if !signed_in? %>
          <%= link_to('Sign Up!', new_user_path)  %>
          <%= link_to('Sign In!', login_path)  %>
		<% else %>
		  Signed in as <%= @current_user.name %>
		  <%= link_to("Sign Out", logout_path) %> 
		  
<%end %>
</nav>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if signed_in? %>
		Signed in as <%= @current_user.name %>
		<img src="@current_user.photo" class="img-circle" alt="Cinque Terre" width="304" height="236">
		<%= link_to "Sign Out", logout_path %>
	<%end %>

</div>

<% flash.each do |key, value|%>
	<div class ="flash <%= key %>">
		<%= value %>
	</div>
<% end %>

<%= yield %>

<footer class="footer">
      <div class="container">
        <p class="text-muted">Sarah Brett C13314646 &copy; 2016 <a href="/#">S|TUNES</a> </p>
		<%=link_to "Contact Us", page_path("about") %>
      </div>
    </footer>
	

</body>
</html>